# -*- coding: utf-8 -*-
"""Merge the per-lever index fragments assets/idx/*.json into assets/index.js (window.D2_INDEX).

Each lever (build_sprites, build_objects, build_world, build_ui) writes only its own fragment and then
calls merge(); the merged file is rebuilt from every fragment each time, so concurrent or repeated runs
converge to the same output. Contract: brain/plans/diablo2-d2r.md, "Hợp đồng v2".
"""
import glob
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.normpath(os.path.join(HERE, '..', 'assets'))
IDX_DIR = os.path.join(ASSETS, 'idx')
OUT = os.path.join(ASSETS, 'index.js')


def deep_merge(a, b, where):
    for k, v in b.items():
        if k in a and isinstance(a[k], dict) and isinstance(v, dict):
            deep_merge(a[k], v, where + '.' + k)
        elif k in a and a[k] != v:
            raise ValueError('index key %s%s set differently by two fragments' % (where, '.' + k))
        else:
            a[k] = v


def write_fragment(name, frag):
    """Write assets/idx/<name>.json (one per lever) and rebuild assets/index.js."""
    os.makedirs(IDX_DIR, exist_ok=True)
    with io.open(os.path.join(IDX_DIR, name + '.json'), 'w', encoding='utf-8', newline='\n') as f:
        json.dump(frag, f, sort_keys=True, separators=(',', ':'))
    merge()


def merge():
    out = {}
    for p in sorted(glob.glob(os.path.join(IDX_DIR, '*.json'))):
        with io.open(p, encoding='utf-8') as f:
            deep_merge(out, json.load(f), os.path.basename(p))
    tmp = OUT + '.tmp'
    with io.open(tmp, 'w', encoding='utf-8', newline='\n') as f:
        f.write(u'// generated by _tools/build_index.py from assets/idx/*.json - do not edit\nwindow.D2_INDEX = ')
        f.write(json.dumps(out, sort_keys=True, separators=(',', ':')))
        f.write(u';\n')
    os.replace(tmp, OUT)
    return out


if __name__ == '__main__':
    idx = merge()
    print('index keys: ' + ', '.join('%s=%d' % (k, len(v) if hasattr(v, '__len__') else 1) for k, v in sorted(idx.items())))
