/* vhud (V01 V02 V08 V09 V13): HUD đồng hồ nửa vòng, chip TAB, thẻ hư hại, hộp hướng dẫn, phím F. Ảnh: %TEMP%/dredge-vhud */
'use strict';
const path = require('path'), http = require('http'), fs = require('fs'), os = require('os');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/tamph/AppData/Roaming/npm/node_modules/@playwright/cli/node_modules/playwright');
const ROOT = path.resolve(__dirname, '..'), OUT = path.join(os.tmpdir(), 'dredge-vhud');
fs.mkdirSync(OUT, { recursive: true });
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.webp': 'image/webp', '.png': 'image/png', '.mp3': 'audio/mpeg', '.ogg': 'audio/ogg', '.woff2': 'font/woff2', '.glb': 'model/gltf-binary', '.bin': 'application/octet-stream' };
const sleep = ms => new Promise(r => setTimeout(r, ms));
let pass = 0, fail = 0;
const ok = (n, c, d) => { c ? pass++ : fail++; console.log((c ? '  ✔ ' : '  ✘ ') + n + (d !== undefined ? '  — ' + JSON.stringify(d) : '')); };
(async () => {
  const srv = await new Promise(r => { const s = http.createServer((q, p) => { const u = decodeURIComponent(q.url.split('?')[0]); fs.readFile(path.join(ROOT, u), (e, b) => { if (e) { p.writeHead(404); p.end(); return; } p.writeHead(200, { 'Content-Type': MIME[path.extname(u)] || 'application/octet-stream', 'Content-Length': b.length }); p.end(b); }); }).listen(0, () => r(s)); });
  const br = await chromium.launch({ args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required'] });
  const page = await (await br.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
  const errs = [];
  page.on('pageerror', e => errs.push(e.message)); page.on('console', m => m.type() === 'error' && errs.push(m.text()));
  page.on('response', r => r.status() >= 400 && errs.push('HTTP ' + r.status() + r.url()));
  await page.goto('http://localhost:' + srv.address().port + '/games/dredge/index.html?fresh=1');
  await page.waitForFunction(() => window.DR_DEBUG && DR_DEBUG.ready(), null, { timeout: 180000 });
  await page.click('#btn-new');
  await page.waitForFunction(() => DR.mode === 'dock', null, { timeout: 15000 });
  await page.evaluate(() => window.DRIntro && DRIntro.playing && DRIntro.skip());
  await page.waitForFunction(() => !(window.DRIntro && DRIntro.playing), null, { timeout: 20000 });
  for (let i = 0; i < 100; i++) { // hội thoại mở đầu
    const s = await page.evaluate(() => { const d = DRDock._debug(); return d && d.phase === 'ui' && !DRDialogue.isOpen(); });
    if (s) break;
    const st = await page.evaluate(() => DRDialogue.isOpen() && DRDialogue.state());
    if (st && st.kind === 'options') await page.click('.dlg-opt[data-index="0"]').catch(() => {}); else await page.keyboard.press('Space');
    await sleep(350);
  }
  await page.evaluate(() => DR.setMode('sail'));
  await page.waitForFunction(() => DRTutorial.debug().showing, null, { timeout: 30000 }).catch(() => {});
  await sleep(500);
  const T = await page.evaluate(() => {
    const r = s => { const e = document.querySelector(s); if (!e) return null; const b = e.getBoundingClientRect(); return { x: Math.round(b.x), y: Math.round(b.y), w: Math.round(b.width), h: Math.round(b.height), vis: getComputedStyle(e).display !== 'none' }; };
    return { day: document.querySelector('.hud-day').textContent, clock: document.querySelector('.hud-tray').textContent, wheel: r('.hud-wheel'), comp: r('.hud-compass'), bag: r('.hud-bag'), funds: !!document.querySelector('.hud-funds'), depth: !!document.querySelector('.hud-depth'), jb: r('.qn-jbtn'), tut: DRTutorial.debug() };
  });
  ok('V01 nhãn ngày "Thứ Hai, Ngày 1"', T.day === 'Thứ Hai, Ngày 1', T.day);
  ok('V01 giờ 24 h dạng HH:MM', /^\d\d:\d\d$/.test(T.clock), T.clock);
  ok('V01 mặt đồng hồ 280 canvas ở giữa trên (1280 -> 187 px)', Math.abs(T.wheel.w - 187) <= 2 && Math.abs(T.wheel.x + T.wheel.w / 2 - 640) <= 2 && T.wheel.y < 0, T.wheel);
  ok('V01 la bàn bên phải mặt đồng hồ (x ~ +186 canvas)', Math.abs(T.comp.x + T.comp.w / 2 - (640 + 186.4 * 0.6667)) <= 3, T.comp);
  ok('V02 không có tiền / độ sâu khi lái', !T.funds && !T.depth);
  ok('V02 không có nút Nhiệm vụ khi lái', !T.jb || !T.jb.vis);
  ok('V02 chip TAB sát mép phải', T.bag && T.bag.x + T.bag.w >= 1279, T.bag);
  ok('V09 hộp hướng dẫn bước 10 hiện sau 1 s lái', T.tut.showing && T.tut.id === 10 && /Tiến/.test(T.tut.text), T.tut);
  await page.screenshot({ path: path.join(OUT, 'tutorial.png') });
  await page.click('.hud-bag');
  await sleep(600);
  ok('V02 bấm chip TAB mở khoang', await page.evaluate(() => DRCargo.isOpen()));
  await page.keyboard.press('Escape'); await sleep(500);
  if (await page.evaluate(() => DRCargo.isOpen())) { await page.keyboard.press('Tab'); await sleep(500); }
  await page.waitForFunction(() => DRTutorial.debug().done.includes(10), null, { timeout: 40000 });
  const t1 = await page.evaluate(() => DRTutorial.debug());
  ok('V09 bước 10 xong và lưu biến tutorial-step-complete-10', t1.done.includes(10) && await page.evaluate(() => DR.s.vars['tutorial-step-complete-10'] === true), t1);
  await sleep(900);
  ok('V09 bước 20 (camera) hiện kế tiếp, bước 10 không lặp lại', await page.evaluate(() => DRTutorial.debug().id) === 20);
  await page.evaluate(() => { DR_DEBUG.hit(); });
  await sleep(500);
  const N = await page.evaluate(() => [...document.querySelectorAll('.hud-note')].map(n => n.textContent));
  ok('V08 thẻ "Thân tàu hư hại" góc trái trên', N.some(x => /Thân tàu hư hại/.test(x)), N);
  const nb = await page.evaluate(() => { const b = document.querySelector('.hud-note').getBoundingClientRect(); return [Math.round(b.x), Math.round(b.y), Math.round(b.width), Math.round(b.height)]; });
  ok('V08 thẻ 250x100 canvas (167x67 px) ở góc trái trên', nb[0] <= 2 && nb[1] <= 10 && Math.abs(nb[2] - 167) <= 3, nb);
  await page.screenshot({ path: path.join(OUT, 'damage.png') });
  await page.evaluate(() => { DR.emit('damage', { cell: [0, 0], destroyed: { id: Object.keys(DR_ITEMS)[0] }, on: null }, 1); });
  await sleep(300);
  ok('V08 mất đồ: "bị mất xuống biển"', (await page.evaluate(() => [...document.querySelectorAll('.hud-note')].map(n => n.textContent))).some(x => /bị mất xuống biển/.test(x)));
  await page.evaluate(() => { const d = DRDocks.byId['dock.greater-marrow']; for (let r = 5; r < 9; r += .5) for (let a = 0; a < 6.28; a += .3) { const x = d.poi.x + Math.cos(a) * r, z = d.poi.z + Math.sin(a) * r; if (DRWorld.sdf(x, z) > 2.5) { DR_DEBUG.teleport(x, z, DR.s.boat.yaw); return; } } });
  await sleep(1500);
  const near = await page.evaluate(() => !!DR.view.nearDock);
  const pr = await page.evaluate(() => document.querySelector('.hud-prompt').textContent);
  ok('V13 gợi ý cập bến ghi phím F', near && /F$/.test(pr.split('Greater')[0].trim()), pr);
  console.log('   paused', await page.evaluate(() => !document.getElementById('dr-pause').hidden));
  await page.keyboard.press('KeyF');
  await page.waitForFunction(() => DR.mode === 'dock', null, { timeout: 60000 }).then(() => ok('V13 F cập bến', true)).catch(() => ok('V13 F cập bến', false));
  await page.evaluate(() => DR.setMode('sail'));
  await sleep(800);
  await page.evaluate(() => { DR.s.sanity = 0.1; });
  await sleep(600);
  const eye = await page.evaluate(() => { const o = document.querySelector('.hud-eye .open'); const b = o.getBoundingClientRect(); return { h: Math.round(b.height), disp: getComputedStyle(o).display, stage: document.querySelector('.hud-eye').dataset.stage }; });
  ok('V01 sanity 0,1: mắt mở 90 canvas (60 px), giai đoạn 4', eye.disp !== 'none' && Math.abs(eye.h - 60) <= 4 && eye.stage === '4', eye);
  await page.screenshot({ path: path.join(OUT, 'panic.png') });
  ok('không có pageerror / console error / HTTP >= 400', errs.length === 0, errs.slice(0, 3));
  console.log(`\n${pass} đạt, ${fail} trượt`);
  await br.close(); srv.close(); process.exit(fail ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
