"""Cá mập trắng lớn (GreatWhiteWorldEvent, R7) -> data/greatwhite.js + art/vfx/greatwhite/{shark.bin,albedo.webp} + audio/monsters/Great_White_-_Swimming_Loop.mp3.

Chạy:  python -I games/dredge/tools/greatwhite.py
Đọc:   Assets/GameObject/GreatWhiteShark.prefab (cây xương, SkinnedMeshRenderer, GreatWhiteWorldEvent.cs, NavMeshAgent, AudioSource),
       Assets/Mesh/GreatWhiteShark.asset, Material/Shark_Mat, AnimatorController/GreatWhiteShark_anim_control, AnimationClip/swim_loop.anim,
       Audio/SFX/World Event/Great White/*.ogg. Điều kiện sinh (Data/WorldEvent/GreatWhite.asset) nằm sẵn ở data/worldevents.js.
Ra:    window.DR_GREATWHITE = { params, curve, bones, skinBones, bindPoses, mesh{url,...}, material, tex, audio, clip }
Bẫy:   (1) clip dùng là swim_loop.anim (guid của Animator controller), KHÔNG phải whaleshark_swimloop.anim (đường dẫn 'headpivot_jnt/...' không khớp cây xương này); công cụ đếm đường cong khớp;
       (2) mesh gốc ở đơn vị cm (nút headtip_jnt có tỉ lệ 0,01): cây xương mang tỉ lệ đó, mesh web đặt ở gốc cảnh với bindpose như tools/phantomshark.py;
       (3) agent NavMesh tốc độ 5 / gia tốc 8 / quay 120°/s: web dùng DRNav.path (js/nav.js) thay cho NavMeshAgent.
Rerunnable: cùng đầu vào ra cùng đầu ra.
"""
import io, os, sys, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import yaml
import leviathan as L

sys.stdout.reconfigure(encoding='utf-8')
GAME, ASSETS = L.GAME, L.ASSETS


def main():
    objs = L.load_doc(os.path.join(ASSETS, 'GameObject', 'GreatWhiteShark.prefab'))
    bones, index, skin_bones, anim_idx, by_path, smr, go_name, tf, go_of_tf = L.skeleton(objs, 'greatwhiteshark', 'GreatWhiteShark')
    pos, uv, idx4, wts, tri, bind, nv = L.read_skinned_mesh(L.guid_path('Mesh', smr['m_Mesh']['guid']))
    assert len(bind) == len(skin_bones)
    outdir = os.path.join(GAME, 'art', 'vfx', 'greatwhite')
    mesh = L.write_bin(os.path.join(outdir, 'shark.bin'), pos, uv, idx4, wts, tri)
    mesh['url'] = 'art/vfx/greatwhite/shark.bin'

    clip = L.curves(os.path.join(ASSETS, 'AnimationClip', 'swim_loop.anim'), 'greatwhiteshark')
    total = sum(len(d) for d in clip['curves'].values())
    miss = L.bind_clip(clip, by_path, anim_idx, 'swim')
    matched = total - miss
    print('swim_loop: %d đường cong, khớp xương %d, không khớp %d' % (total, matched, miss))
    clip_out = {'len': clip['len'], 'loop': clip['loop'], 'matched': matched, 'curves': clip['curves'] if matched else {}}

    mono = [o[1] for o in objs.values() if o[0] == 114 and 'playerDistanceThreshold' in o[1]][0]
    nav = [o[1] for o in objs.values() if o[0] == 195][0]
    au = [o[1] for o in objs.values() if o[0] == 82][0]
    params = {k: float(mono[k]) for k in ('waypointDistanceThreshold', 'playerDistanceThreshold', 'despawnDistanceThreshold', 'downY', 'idleSpeed', 'pursueSpeed',
                                         'maxSeekTimeSec', 'rotationSpeed')}
    params.update({'accel': float(nav['m_Acceleration']), 'angular': float(nav['m_AngularSpeed']), 'radius': float(nav['m_Radius']),
                   'riseSec': 2.0, 'fadeInSec': 1.0, 'forceDespawnSec': 3.0, 'audioMin': float(au['MinDistance']), 'audioMax': float(au['MaxDistance'])})
    model_idx = anim_idx   # 'greatwhiteshark' (nút có Animator; GreatWhiteWorldEvent.model)
    curve = L.anim_curve(mono['playerProximityDepth'])

    mat = list(yaml.load(io.open(L.guid_path('Material', smr['m_Materials'][0]['guid']), encoding='utf-8').read().split('\n', 3)[3], Loader=L.CL).values())[0]['m_SavedProperties']
    tbytes = L.save_tex(L.guid_path('Texture2D', [t['m_Texture']['guid'] for t in mat['m_TexEnvs'].values() if t['m_Texture'].get('guid')][0]), outdir, 'albedo')

    e = L.encode_audio('Great White/Great White - Swimming_Loop 1.ogg', 'Great_White_-_Swimming_Loop', '32k')
    abytes = e.pop('bytes')
    e.update({'loop': True, 'vol': 0.8})
    data = {'src': 'GameObject/GreatWhiteShark.prefab (GreatWhiteWorldEvent.cs, GreatWhiteShark.asset, Shark_Mat)', 'params': params, 'curve': curve,
            'bones': bones, 'skinBones': skin_bones, 'modelNode': model_idx, 'bindPoses': bind, 'mesh': mesh, 'clip': clip_out,
            'tex': {'albedo': 'art/vfx/greatwhite/albedo.webp'}, 'audio': {'event.greatwhite.loop': e}}
    js = '// Generated by games/dredge/tools/greatwhite.py from GreatWhiteShark.prefab. Do not edit.\nwindow.DR_GREATWHITE = ' + json.dumps(data, separators=(',', ':')) + ';\n'
    io.open(os.path.join(GAME, 'data', 'greatwhite.js'), 'w', encoding='utf-8', newline='\n').write(js)
    print('bones %d verts %d tris %d  js %d KB  bin %d KB  tex %d KB  audio %d KB' % (len(bones), nv, tri.size // 3, len(js) // 1024, mesh['bytes'] // 1024, tbytes // 1024, abytes // 1024))


if __name__ == '__main__':
    main()
