"""Điểm kiểm tra (InspectPOI: phao, xác tàu, bia đá, kho bờ biển) -> data/poi.js  (V17).

Chạy:  python -I games/dredge/tools/poi.py          (vài giây; cần art/world/markers.json do tools/world.py ghi)
Đọc:   art/world/markers.json: mọi marker kind 'inspectPOI' (con của InspectPOIs / DLC1/InspectPOI trong Game.unity) mang script InspectPOI
       (ConversationPOI.cs: conversationNodeName, isOneTimeOnly, enabledByOtherNodeVisit + enableNodeNames, shouldDisableOnOtherNodeVisit + otherNodeNames,
       interactCollider) và SphereCollider tương tác (bán kính).
Ra:    window.DR_POI = { points: [{ id, zone, x, z, r, node, once, needs[], hideAfter[] }], items: [{ id, item, x, z, r }] }   (x, z = three.js: z đã đảo dấu trong markers.json)
       items = ItemPOI (chai thư: tên GameObject "[số] <itemId> 1/1" do ItemPOI.OnValidate đặt; kho 1 món, ItemPOIDataModel.GetStartStock = 1; r = SphereCollider poiCollider)
Bỏ:    marker không có InspectPOI (SKUSpecificDisabler / MapMarkerLocation trơn: chỉ để bật tắt theo bản demo), AutoMovePOI (Finale_Inspect: cảnh cuối).
Bẫy:   `[BẪY ĐÃ SẬP]` ConversationPOI.RefreshStatus tắt cả GameObject khi đã thăm nút một lần (isOneTimeOnly) HOẶC khi bất kỳ nút trong otherNodeNames
       đã thăm; các kho bờ biển (xxShoreCache) dùng cách thứ hai (nút `..._Emptied` chạy khi lưới Found Items trống) nên KHÔNG tắt khi chỉ mới ghé.
       Rerunnable: cùng đầu vào ra cùng đầu ra.
"""
import io, os, json, sys, re

sys.stdout.reconfigure(encoding='utf-8')
HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
SRC = os.path.join(GAME, 'art', 'world', 'markers.json')
OUT = os.path.join(GAME, 'data', 'poi.js')


def main():
    markers = json.load(io.open(SRC, encoding='utf-8'))['markers']
    pts = []
    for m in markers:
        if m['kind'] != 'inspectPOI':
            continue
        f = (m.get('fields') or {}).get('InspectPOI')
        if not f or not f.get('conversationNodeName'):
            continue
        sph = [c for c in m.get('colliders', []) if c.get('shape') == 'sphere']
        if not sph:
            raise SystemExit('InspectPOI %s has no sphere collider' % m['path'])
        pts.append({
            'id': m['name'], 'zone': m['root'], 'x': round(m['pos'][0], 2), 'z': round(m['pos'][2], 2), 'r': sph[0]['radius'],
            'node': f['conversationNodeName'], 'once': bool(f.get('isOneTimeOnly')),
            'needs': f.get('enableNodeNames') or [] if f.get('enabledByOtherNodeVisit') else [],
            'hideAfter': f.get('otherNodeNames') or [] if f.get('shouldDisableOnOtherNodeVisit') else [],
        })
    pts.sort(key=lambda p: (p['zone'], p['id']))
    items = []
    for m in markers:
        if 'ItemPOI' not in (m.get('scripts') or []):
            continue
        mm = re.match(r'^\[(\d+)\] (\S+) (\d+)/(\d+)$', m['name'])
        sph = [c for c in m.get('colliders', []) if c.get('shape') == 'sphere']
        if not mm or not sph:
            raise SystemExit('ItemPOI %s has no parsable name or sphere collider' % m['path'])
        items.append({'id': mm.group(1), 'item': mm.group(2), 'x': round(m['pos'][0], 2), 'z': round(m['pos'][2], 2), 'r': sph[0]['radius']})
    items.sort(key=lambda p: int(p['id']))
    js = '// Generated by games/dredge/tools/poi.py from art/world/markers.json (InspectPOI, ItemPOI). Do not edit.\nwindow.DR_POI = ' + \
        json.dumps({'points': pts, 'items': items}, separators=(',', ':'), ensure_ascii=False) + ';\n'
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(js)
    print('points %d  items %d  js %d B' % (len(pts), len(items), len(js)))


if __name__ == '__main__':
    main()
