"""Vùng an toàn (layer 27 'SafeZone') của sự kiện thế giới -> data/safezones.js.

Chạy:  python -I games/dredge/tools/safezones.py          (~1 phút: nạp scene Game.unity qua tools/world.py)
Đọc:   mọi GameObject có m_Layer == 27 trong scene Game, và các collider của nó (Box/Sphere/Capsule/Mesh).
       WorldEventManager.DoesHitSafeZone (WorldEventManager.cs:451-455) bắn tia xuống từ y = 9999 theo layer này, nên chỉ hình chiếu XZ của
       collider là quan trọng; trigger cũng tính (RaycastAll mặc định trúng trigger).
Ra:    window.DR_SAFEZONES = { count, zones: [ { name, path, active, shape, pos[x,y,z], rotY, scale[3], center, size | radius,height,direction | outlineXZ, ... } ] }
Toạ độ: three.js (z âm so với Unity), như markers.json. Rerunnable: sắp theo path, làm tròn 3 chữ số.
"""
import io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import world  # noqa: E402  (có if __name__ guard)

sys.stdout.reconfigure(encoding='utf-8')
LAYER = 27  # TagManager: 'SafeZone'


def r3(v):
    if isinstance(v, float):
        x = round(v, 3)
        return 0.0 if x == 0 else x
    if isinstance(v, (list, tuple)):
        return [r3(a) for a in v]
    if isinstance(v, dict):
        return {k: r3(a) for k, a in v.items()}
    return v


def main():
    S = world.Scene(world.load_env())
    M = world.Meshes()
    names = None
    try:
        import UnityPy
        env = UnityPy.load(os.path.join(world.DATA, 'globalgamemanagers'))
        for o in env.objects:
            if o.type.name == 'TagManager':
                names = o.parse_as_dict()['layers']
    except Exception as e:  # noqa: BLE001
        print('không đọc được TagManager:', e)
    if names:
        assert names[LAYER] == 'SafeZone', 'layer %d là %r' % (LAYER, names[LAYER])
    zones = []
    for g, d in S.G.items():
        if d.get('m_Layer') != LAYER:
            continue
        for v in world.collider_volumes(S, M, g):
            v = dict(v)
            v['name'] = S.name(g)
            v['path'] = S.path(g)
            v['active'] = S.active(g)
            zones.append(v)
    zones.sort(key=lambda z: (z['path'], z['shape'], str(z.get('center')), str(z['pos'])))
    zones = [dict(r3(z), rotY=round(z['rotY'], 5)) for z in zones]  # rotY giữ 5 chữ số (hộp 50 m: 0,0004 rad = 2 cm)
    out = os.path.join(os.path.dirname(HERE), 'data', 'safezones.js')
    with io.open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// generated by tools/safezones.py - do not edit\n')
        f.write('window.DR_SAFEZONES = ' + json.dumps({'count': len(zones), 'layer': LAYER, 'zones': zones}, ensure_ascii=False, indent=1) + ';\n')
    print('SafeZone colliders:', len(zones), '| active', sum(z['active'] for z in zones))
    for z in zones:
        print(' ', z['shape'], z['active'], z['path'], z['pos'])


if __name__ == '__main__':
    main()
