# -*- coding: utf-8 -*-
"""Cần bóc dữ liệu thẻ / quái / chế độ chơi của The Bazaar Demo ra JS cho web.

Chạy lại (Python 3.12 vì bảng SQLite dùng STRICT, Python 3.8 không mở được):

    py -3.12 -I games/bazaar/tools/data.py [--db D:\\bazaar-ref\\db\\GameData.db]

Nguồn: `GameData.db` (mỗi dòng là JSON). Nếu không truyền --db: dùng `D:\\bazaar-ref\\db\\GameData.db`,
không có thì giải nén `GameData.db.zip` từ thư mục Steam vào `D:\\bazaar-ref\\db\\` (không ghi gì vào Steam).

Ra (trong repo, cạnh thư mục tools):
- data/cards.js    window.BZ_CARDS    = {Id: template}  TCardItem + TCardSkill của Vanessa, Pygmalien, Dooley,
                                                       Common + mọi thẻ mà quái trong monsters dùng
- data/monsters.js window.BZ_MONSTERS = [monster...]    + trường suy ra `Encounters` (các thẻ TCardEncounterCombat
                                                       trỏ tới quái đó: tên hiển thị, bậc, Level, vàng/XP thưởng)
- data/mode.js     window.BZ_MODE     = {mode, levelUps, tooltips}
- data/encounters.js window.BZ_ENCOUNTERS = {events, steps, pedestals, combats}  thẻ gặp gỡ cho vòng chơi (js/run):
                                                       Kind suy ra (merchant/pile/instant/choice/unknown), Steps nối theo tên,
                                                       Days từ tên "(Day 4-6)"; chi tiết ở write_encounters()

DSL giữ nguyên tên `$type` và tên trường; chỉ bỏ những gì runtime không dùng:
InternalDescription, MigrationData, TranslationKey, Version, TemplateVersion, khoá dịch `Key`,
VFXConfig khi là mặc định (VFXOverrideKey null, VFXShouldPlay true, VFXIsTakeover false), HasAbilities/HasAuras.
mọi trường null (thiếu = null), InternalName của ability/aura (giữ ở cấp thẻ).
Giữ chuỗi `Text` của tooltip. Khối Enchantments trùng nhau được ghi một lần rồi nối lại khi nạp. JSON gọn (không thụt lề), khoá giữ thứ tự gốc nên chạy lại ra cùng tệp.
"""
import collections
import io
import json
import os
import re
import sqlite3
import sys
import zipfile

sys.stdout.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "data")
DEFAULT_DB = r"D:\bazaar-ref\db\GameData.db"
STEAM_ZIP = r"D:\Steam\steamapps\common\The Bazaar Demo\TheBazaar_Data\StreamingAssets\GameData.db.zip"
HEROES = {"Vanessa", "Pygmalien", "Dooley", "Common"}
DROP_KEYS = {"InternalDescription", "MigrationData", "TranslationKey", "Version", "TemplateVersion",
             "HasAbilities", "HasAuras"}
GLOBAL = "(typeof window!=='undefined'?window:globalThis)"


def open_db(path):
    if path is None:
        path = DEFAULT_DB
        if not os.path.exists(path):
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with zipfile.ZipFile(STEAM_ZIP) as z:
                name = [n for n in z.namelist() if n.endswith(".db")][0]
                with z.open(name) as src, open(path, "wb") as dst:
                    dst.write(src.read())
    return sqlite3.connect("file:" + path + "?mode=ro", uri=True), path


def rows(con, table):
    return [json.loads(bytes(r[0]).decode("utf-8")) for r in con.execute(f"select Data from {table} order by Id")]


def is_default_vfx(v):
    return isinstance(v, dict) and v.get("VFXOverrideKey") is None and v.get("VFXShouldPlay", True) is True \
        and not v.get("VFXIsTakeover", False)


def strip(o, top=True):
    """Bỏ trường không cần cho runtime, giữ nguyên phần còn lại. Trường null bị bỏ (runtime coi thiếu = null);
    InternalName chỉ giữ ở cấp thẻ/quái (tên nội bộ của từng ability/aura chỉ để gỡ lỗi)."""
    if isinstance(o, dict):
        out = {}
        for k, v in o.items():
            if k in DROP_KEYS or v is None:
                continue
            if k == "InternalName" and not top:
                continue
            if k == "VFXConfig" and is_default_vfx(v):
                continue
            if k == "Key" and isinstance(v, str) and "Text" in o:
                continue  # khoá dịch của TLocalizableText, giữ Text
            out[k] = strip(v, False)
        return out
    if isinstance(o, list):
        return [strip(v, False) for v in o]
    if isinstance(o, float) and o.is_integer():
        return int(o)  # 3.0 -> 3: gọn hơn, giá trị như nhau trong JS
    return o


def dump(obj):
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def write_js(name, var, obj, note, ench=None):
    path = os.path.join(OUT, name)
    head = (f"/* generated by games/bazaar/tools/data.py from GameData.db (The Bazaar Demo) - do not edit.\n"
            f"   {note}\n"
            f"   Rerun: py -3.12 -I games/bazaar/tools/data.py */\n")
    if ench is None:
        body = head + f"{GLOBAL}.{var}={dump(obj)};\n"
    else:
        # Khối enchantment trùng nhau giữa các thẻ (~9700 khối, ~1900 khác nhau): ghi một lần vào E,
        # thẻ giữ chỉ số; vòng lặp nhỏ dưới đây trả lại đúng hình gốc Enchantments{tên: khối} khi nạp.
        body = head + ("(function(g){var E=" + dump(ench) + ";\nvar C=" + dump(obj) + ";\n"
                       "for(var id in C){var en=C[id].Enchantments;if(en)for(var k in en)en[k]=E[en[k]];}"
                       f"g.{var}=C;}})({GLOBAL});\n")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    return path, len(body.encode("utf-8"))


ENC_DROP = re.compile(r"DEBUG|Debug|TEMPLATE|Tutorial|DEFUNCT|Internal Only|Expedition|Start Run|Start Skill")
DAYS_RE = re.compile(r"\(Day (\d+)(?:\s*(?:-|to|and Day)\s*(\d+))?(\+)?\)")


def loc_text(c, key):
    return ((c.get("Localization") or {}).get(key) or {}).get("Text")


def enc_days(name):
    """"Cache of Riches (Day 1 to 2)" -> [1, 2]; "(Day 5+)" -> [5, 99]; "(Day 9)" -> [9, 9]; không có -> None."""
    m = DAYS_RE.search(name or "")
    if not m:
        return None
    lo = int(m.group(1))
    hi = int(m.group(2)) if m.group(2) else (99 if m.group(3) else lo)
    return [lo, hi]


def step_key(name):
    """Khoá nối bước (TCardEncounterStep) về sự kiện cha: NextEncounterOnSelection bị máy chủ xoá ([BazaarObfuscate]),
    nhưng tên nội bộ mang tên sự kiện: "[Bex] 1st Quarter", "Upgrade (Botul)", "Haddy - Bag of Gold"."""
    m = re.match(r"^\[([^\]]+)\]", name) or re.search(r"\(([^()]+)\)\s*$", name)
    if m:
        return m.group(1)
    if " - " in name:
        return name.rsplit(" - ", 1)[0]
    return None


def enc_limit(sc):
    lim = ((sc or {}).get("SpawnContext") or {}).get("Limit") or {}
    if lim.get("$type") == "TRangeValue":
        return [int(lim.get("MinValue") or 0), int(lim.get("MaxValue") or 0)]
    v = lim.get("Value")
    return int(v) if v is not None else None


def write_encounters(cards):
    """data/encounters.js cho vòng chơi (games/bazaar/js/run). Mỗi bản ghi gọn: Id, InternalName, Title, Desc, StartingTier,
    Heroes, Tags, ArtKey, Xp (= ExperienceAwardUponSelection), Days (từ tên), LevelUp (tên có "(Level Up)").
    - events: Kind = merchant (Tags Merchant hoặc "Sells ..."), instant (không có SelectionContext: ability chạy khi chọn),
      pile (chọn miễn phí: SelectionIsFree), choice (chọn có bước con nối được theo tên), unknown (bước con không nối được).
      Rules = SelectionContext.Rules, Limit = số thẻ bày ra (TRangeValue -> [min, max]).
    - steps: bước con được sự kiện giữ lại + mọi bước "(Level Up)"; Abilities giữ nguyên DSL (đã strip).
    - pedestals: Criteria = SelectionCriteria (DSL TCardConditional*); Behavior bị xoá -> js/run suy ra từ Desc.
    - combats: thẻ quái (MonsterTemplateId, Level, vàng/XP thưởng) — monsters.js cũng có trường Encounters tương tự.
    Bỏ bản DEBUG/Tutorial/DEFUNCT/Expedition/Internal/Start Run (không vào được vòng chơi web)."""
    by_name = collections.defaultdict(list)
    events, steps, peds, combats = {}, {}, {}, {}
    all_steps = [c for c in cards if c["$type"] == "TCardEncounterStep"]

    def base(c):
        o = {"Id": c["Id"], "InternalName": c.get("InternalName"), "Title": loc_text(c, "Title"),
             "Desc": loc_text(c, "Description"), "StartingTier": c.get("StartingTier"), "Heroes": c.get("Heroes") or [],
             "Tags": c.get("Tags") or [], "ArtKey": c.get("ArtKey"), "Xp": c.get("ExperienceAwardUponSelection") or 0}
        d = enc_days(c.get("InternalName"))
        if d:
            o["Days"] = d
        if "(Level Up)" in (c.get("InternalName") or ""):
            o["LevelUp"] = True
        if c.get("Abilities"):
            o["Abilities"] = strip(c["Abilities"], False)
        return o

    for c in cards:
        if c["$type"] != "TCardEncounterEvent" or ENC_DROP.search(c.get("InternalName") or ""):
            continue
        o = base(c)
        sc = c.get("SelectionContext")
        if sc:
            o["Rules"] = strip(sc.get("Rules") or {}, False)
            o["Limit"] = enc_limit(sc)
        desc = o["Desc"] or ""
        if "Merchant" in o["Tags"] or (sc and desc.startswith("Sells ")):
            o["Kind"] = "merchant"
        elif not sc:
            o["Kind"] = "instant"
        elif (sc.get("Rules") or {}).get("SelectionIsFree"):
            o["Kind"] = "pile"
        else:
            o["Kind"] = "unknown"  # thành "choice" nếu nối được bước con bên dưới
        events[c["Id"]] = o
        by_name[c["InternalName"]].append(c["Id"])
        if o["Title"] and o["Title"] != c["InternalName"]:
            by_name[o["Title"]].append(c["Id"])

    linked = 0
    for s in all_steps:
        name = s.get("InternalName") or ""
        if ENC_DROP.search(name):
            continue
        key = step_key(name)
        parents = [p for p in by_name.get(key, []) if events[p]["Kind"] in ("unknown", "choice")] if key else []
        if not parents and "(Level Up)" not in name:
            continue
        steps[s["Id"]] = base(s)
        for p in parents:
            ev = events[p]
            ev["Kind"] = "choice"
            ev.setdefault("Steps", []).append(s["Id"])
            linked += 1

    for c in cards:
        if c["$type"] == "TCardEncounterPedestal" and not ENC_DROP.search(c.get("InternalName") or ""):
            o = base(c)
            o["Criteria"] = strip(c.get("SelectionCriteria"), False)
            peds[c["Id"]] = o
        elif c["$type"] == "TCardEncounterCombat" and not ENC_DROP.search(c.get("InternalName") or ""):
            ct = c.get("CombatantType") or {}
            if not ct.get("MonsterTemplateId"):
                continue
            o = base(c)
            o.update({"Monster": ct.get("MonsterTemplateId"), "Level": ct.get("Level"),
                      "Gold": c.get("RewardCombatGold") or 0, "XpReward": c.get("RewardCombatXp") or 0})
            combats[c["Id"]] = o

    data = {"events": events, "steps": steps, "pedestals": peds, "combats": combats}
    kinds = collections.Counter(e["Kind"] for e in events.values())
    note = (f"{len(events)} events ({', '.join(f'{k} {v}' for k, v in sorted(kinds.items()))}), {len(steps)} steps "
            f"({linked} links by name), {len(peds)} pedestals, {len(combats)} combats.")
    p, n = write_js("encounters.js", "BZ_ENCOUNTERS", data, note)
    print("encounters:", note)
    print(f"{p}: {n} bytes ({n / 1048576:.2f} MB)")


def main():
    db = None
    if "--db" in sys.argv:
        db = sys.argv[sys.argv.index("--db") + 1]
    con, dbpath = open_db(db)
    cards = rows(con, "cards")
    monsters = rows(con, "monsters")
    modes = rows(con, "game_modes")
    levelups = sorted(rows(con, "level_ups"), key=lambda r: r["Level"])
    tooltips = rows(con, "tooltips")
    byid = {c["Id"]: c for c in cards}

    picked = []
    for c in cards:
        if c["$type"] in ("TCardItem", "TCardSkill") and HEROES & set(c.get("Heroes") or []):
            picked.append(c["Id"])
    ref, missing = [], []
    for m in monsters:
        p = m["Player"]
        insts = list(p["Hand"].get("Items") or []) + list((p.get("Stash") or {}).get("Items") or []) \
            + list(p.get("Skills") or [])
        for it in insts:
            tid = it["TemplateId"]
            if tid in byid:
                ref.append(tid)
            else:
                missing.append((m["InternalName"], tid))
    keep = set(picked) | set(ref)
    out_cards, ench, ench_idx = {}, [], {}
    for c in cards:  # thứ tự theo Id của bảng: ổn định giữa các lần chạy
        if c["Id"] in keep:
            sc = strip(c)
            for name, block in (sc.get("Enchantments") or {}).items():
                key = dump(block)
                if key not in ench_idx:
                    ench_idx[key] = len(ench)
                    ench.append(block)
                sc["Enchantments"][name] = ench_idx[key]
            out_cards[c["Id"]] = sc

    enc = {}
    for c in cards:
        if c["$type"] != "TCardEncounterCombat":
            continue
        ct = c.get("CombatantType") or {}
        mid = ct.get("MonsterTemplateId")
        if not mid:
            continue
        title = ((c.get("Localization") or {}).get("Title") or {}).get("Text")
        enc.setdefault(mid, []).append({
            "Id": c["Id"], "InternalName": c.get("InternalName"), "Title": title,
            "StartingTier": c.get("StartingTier"), "Level": ct.get("Level"),
            "RewardCombatGold": c.get("RewardCombatGold"), "RewardCombatXp": c.get("RewardCombatXp"),
            "SandstormEnabled": c.get("SandstormEnabled"), "ArtKey": c.get("ArtKey"),
        })
    out_mons = []
    for m in monsters:
        sm = strip(m)
        sm["Encounters"] = enc.get(m["Id"], [])
        out_mons.append(sm)

    mode = {"mode": strip(modes[0]), "levelUps": strip(levelups), "tooltips": strip(tooltips[0])}

    os.makedirs(OUT, exist_ok=True)
    n_items = sum(1 for c in out_cards.values() if c["$type"] == "TCardItem")
    n_skills = len(out_cards) - n_items
    r1 = write_js("cards.js", "BZ_CARDS", out_cards,
                  f"{len(out_cards)} templates ({n_items} TCardItem, {n_skills} TCardSkill): heroes "
                  f"{', '.join(sorted(HEROES))} + every card used by a monster; {len(ench)} distinct enchantment blocks.",
                  ench)
    r2 = write_js("monsters.js", "BZ_MONSTERS", out_mons,
                  f"{len(out_mons)} monsters; Encounters = TCardEncounterCombat cards pointing at each (derived).")
    r3 = write_js("mode.js", "BZ_MODE", mode, "TGameMode + level_ups + tooltips keyword glossary.")
    print("db:", dbpath)
    print(f"cards: {len(out_cards)} (items {n_items}, skills {n_skills}; hero pick {len(picked)}, "
          f"monster refs {len(set(ref))}, missing template ids {len(missing)})")
    for mn, tid in missing:
        print("  missing:", mn, tid)
    print(f"monsters: {len(out_mons)} (with encounter card: {sum(1 for m in out_mons if m['Encounters'])})")
    for p, n in (r1, r2, r3):
        print(f"{p}: {n} bytes ({n / 1048576:.2f} MB)")
    write_encounters(cards)


if __name__ == "__main__":
    main()
