# -*- coding: utf-8 -*-
"""Cần bóc dữ liệu thẻ / quái / chế độ chơi của The Bazaar Demo ra JS cho web.

Chạy lại (Python 3.12 vì bảng SQLite dùng STRICT, Python 3.8 không mở được):

    py -3.12 -I games/bazaar/tools/data.py [--db D:\\bazaar-ref\\db\\GameData.db]

Nguồn: `GameData.db` (mỗi dòng là JSON). Nếu không truyền --db: dùng `D:\\bazaar-ref\\db\\GameData.db`,
không có thì giải nén `GameData.db.zip` từ thư mục Steam vào `D:\\bazaar-ref\\db\\` (không ghi gì vào Steam).

Ra (trong repo, cạnh thư mục tools):
- data/cards.js    window.BZ_CARDS    = {Id: template}  TCardItem + TCardSkill của Vanessa, Pygmalien, Dooley,
                                                       Common + mọi thẻ mà quái trong monsters dùng
- data/monsters.js window.BZ_MONSTERS = [monster...]    + trường suy ra `Encounters` (các thẻ TCardEncounterCombat
                                                       trỏ tới quái đó: tên hiển thị, bậc, Level, vàng/XP thưởng)
- data/mode.js     window.BZ_MODE     = {mode, levelUps, tooltips}

DSL giữ nguyên tên `$type` và tên trường; chỉ bỏ những gì runtime không dùng:
InternalDescription, MigrationData, TranslationKey, Version, TemplateVersion, khoá dịch `Key`,
VFXConfig khi là mặc định (VFXOverrideKey null, VFXShouldPlay true, VFXIsTakeover false), HasAbilities/HasAuras.
mọi trường null (thiếu = null), InternalName của ability/aura (giữ ở cấp thẻ).
Giữ chuỗi `Text` của tooltip. Khối Enchantments trùng nhau được ghi một lần rồi nối lại khi nạp. JSON gọn (không thụt lề), khoá giữ thứ tự gốc nên chạy lại ra cùng tệp.
"""
import io
import json
import os
import sqlite3
import sys
import zipfile

sys.stdout.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "data")
DEFAULT_DB = r"D:\bazaar-ref\db\GameData.db"
STEAM_ZIP = r"D:\Steam\steamapps\common\The Bazaar Demo\TheBazaar_Data\StreamingAssets\GameData.db.zip"
HEROES = {"Vanessa", "Pygmalien", "Dooley", "Common"}
DROP_KEYS = {"InternalDescription", "MigrationData", "TranslationKey", "Version", "TemplateVersion",
             "HasAbilities", "HasAuras"}
GLOBAL = "(typeof window!=='undefined'?window:globalThis)"


def open_db(path):
    if path is None:
        path = DEFAULT_DB
        if not os.path.exists(path):
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with zipfile.ZipFile(STEAM_ZIP) as z:
                name = [n for n in z.namelist() if n.endswith(".db")][0]
                with z.open(name) as src, open(path, "wb") as dst:
                    dst.write(src.read())
    return sqlite3.connect("file:" + path + "?mode=ro", uri=True), path


def rows(con, table):
    return [json.loads(bytes(r[0]).decode("utf-8")) for r in con.execute(f"select Data from {table} order by Id")]


def is_default_vfx(v):
    return isinstance(v, dict) and v.get("VFXOverrideKey") is None and v.get("VFXShouldPlay", True) is True \
        and not v.get("VFXIsTakeover", False)


def strip(o, top=True):
    """Bỏ trường không cần cho runtime, giữ nguyên phần còn lại. Trường null bị bỏ (runtime coi thiếu = null);
    InternalName chỉ giữ ở cấp thẻ/quái (tên nội bộ của từng ability/aura chỉ để gỡ lỗi)."""
    if isinstance(o, dict):
        out = {}
        for k, v in o.items():
            if k in DROP_KEYS or v is None:
                continue
            if k == "InternalName" and not top:
                continue
            if k == "VFXConfig" and is_default_vfx(v):
                continue
            if k == "Key" and isinstance(v, str) and "Text" in o:
                continue  # khoá dịch của TLocalizableText, giữ Text
            out[k] = strip(v, False)
        return out
    if isinstance(o, list):
        return [strip(v, False) for v in o]
    if isinstance(o, float) and o.is_integer():
        return int(o)  # 3.0 -> 3: gọn hơn, giá trị như nhau trong JS
    return o


def dump(obj):
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def write_js(name, var, obj, note, ench=None):
    path = os.path.join(OUT, name)
    head = (f"/* generated by games/bazaar/tools/data.py from GameData.db (The Bazaar Demo) - do not edit.\n"
            f"   {note}\n"
            f"   Rerun: py -3.12 -I games/bazaar/tools/data.py */\n")
    if ench is None:
        body = head + f"{GLOBAL}.{var}={dump(obj)};\n"
    else:
        # Khối enchantment trùng nhau giữa các thẻ (~9700 khối, ~1900 khác nhau): ghi một lần vào E,
        # thẻ giữ chỉ số; vòng lặp nhỏ dưới đây trả lại đúng hình gốc Enchantments{tên: khối} khi nạp.
        body = head + ("(function(g){var E=" + dump(ench) + ";\nvar C=" + dump(obj) + ";\n"
                       "for(var id in C){var en=C[id].Enchantments;if(en)for(var k in en)en[k]=E[en[k]];}"
                       f"g.{var}=C;}})({GLOBAL});\n")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    return path, len(body.encode("utf-8"))


def main():
    db = None
    if "--db" in sys.argv:
        db = sys.argv[sys.argv.index("--db") + 1]
    con, dbpath = open_db(db)
    cards = rows(con, "cards")
    monsters = rows(con, "monsters")
    modes = rows(con, "game_modes")
    levelups = sorted(rows(con, "level_ups"), key=lambda r: r["Level"])
    tooltips = rows(con, "tooltips")
    byid = {c["Id"]: c for c in cards}

    picked = []
    for c in cards:
        if c["$type"] in ("TCardItem", "TCardSkill") and HEROES & set(c.get("Heroes") or []):
            picked.append(c["Id"])
    ref, missing = [], []
    for m in monsters:
        p = m["Player"]
        insts = list(p["Hand"].get("Items") or []) + list((p.get("Stash") or {}).get("Items") or []) \
            + list(p.get("Skills") or [])
        for it in insts:
            tid = it["TemplateId"]
            if tid in byid:
                ref.append(tid)
            else:
                missing.append((m["InternalName"], tid))
    keep = set(picked) | set(ref)
    out_cards, ench, ench_idx = {}, [], {}
    for c in cards:  # thứ tự theo Id của bảng: ổn định giữa các lần chạy
        if c["Id"] in keep:
            sc = strip(c)
            for name, block in (sc.get("Enchantments") or {}).items():
                key = dump(block)
                if key not in ench_idx:
                    ench_idx[key] = len(ench)
                    ench.append(block)
                sc["Enchantments"][name] = ench_idx[key]
            out_cards[c["Id"]] = sc

    enc = {}
    for c in cards:
        if c["$type"] != "TCardEncounterCombat":
            continue
        ct = c.get("CombatantType") or {}
        mid = ct.get("MonsterTemplateId")
        if not mid:
            continue
        title = ((c.get("Localization") or {}).get("Title") or {}).get("Text")
        enc.setdefault(mid, []).append({
            "Id": c["Id"], "InternalName": c.get("InternalName"), "Title": title,
            "StartingTier": c.get("StartingTier"), "Level": ct.get("Level"),
            "RewardCombatGold": c.get("RewardCombatGold"), "RewardCombatXp": c.get("RewardCombatXp"),
            "SandstormEnabled": c.get("SandstormEnabled"), "ArtKey": c.get("ArtKey"),
        })
    out_mons = []
    for m in monsters:
        sm = strip(m)
        sm["Encounters"] = enc.get(m["Id"], [])
        out_mons.append(sm)

    mode = {"mode": strip(modes[0]), "levelUps": strip(levelups), "tooltips": strip(tooltips[0])}

    os.makedirs(OUT, exist_ok=True)
    n_items = sum(1 for c in out_cards.values() if c["$type"] == "TCardItem")
    n_skills = len(out_cards) - n_items
    r1 = write_js("cards.js", "BZ_CARDS", out_cards,
                  f"{len(out_cards)} templates ({n_items} TCardItem, {n_skills} TCardSkill): heroes "
                  f"{', '.join(sorted(HEROES))} + every card used by a monster; {len(ench)} distinct enchantment blocks.",
                  ench)
    r2 = write_js("monsters.js", "BZ_MONSTERS", out_mons,
                  f"{len(out_mons)} monsters; Encounters = TCardEncounterCombat cards pointing at each (derived).")
    r3 = write_js("mode.js", "BZ_MODE", mode, "TGameMode + level_ups + tooltips keyword glossary.")
    print("db:", dbpath)
    print(f"cards: {len(out_cards)} (items {n_items}, skills {n_skills}; hero pick {len(picked)}, "
          f"monster refs {len(set(ref))}, missing template ids {len(missing)})")
    for mn, tid in missing:
        print("  missing:", mn, tid)
    print(f"monsters: {len(out_mons)} (with encounter card: {sum(1 for m in out_mons if m['Encounters'])})")
    for p, n in (r1, r2, r3):
        print(f"{p}: {n} bytes ({n / 1048576:.2f} MB)")


if __name__ == "__main__":
    main()
